#!/bin/sh
set -e

lb config noauto \
    --distribution bookworm \
    --archive-areas "main contrib non-free non-free-firmware" \
    --linux-flavours amd64 \
    --bootloaders "syslinux grub-efi" \
    --binary-images iso-hybrid \
    --memtest none \
    --firmware-binary true \
    --firmware-chroot true \
    --security true \
    --updates true \
    --backports true \
    --source false \
    --iso-application "macOS-like Live" \
    --iso-publisher "Custom Build" \
    --iso-volume "macOS-like $(date +%Y%m%d)" \
    --bootappend-live "boot=live components quiet splash username=macuser user-fullname='Mac User' hostname=maclike locales=en_US.UTF-8 keyboard-layouts=us timezone=UTC" \
    "$@"
